# ===========================================
# Private Registry Deployment
# ===========================================
# 용도: 폐쇄망 환경에서 컨테이너 이미지 저장소 역할
# 접근: http://192.168.2.2:32000
# ===========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
          name: http
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: registry-data
        emptyDir: {}  # 운영환경에서는 PVC로 변경 필요
---
# ===========================================
# Private Registry Service
# ===========================================
# NodePort 32000으로 외부 접근 허용
# ===========================================
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32000
    name: http
  selector:
    app: registry