apiVersion: v2
name: container-platform
description: 동적 컨테이너 개발환경 플랫폼
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: devsyw
keywords:
  - container
  - development
  - vscode
  - jupyter

# JupyterHub dependency 추가
dependencies:
  - name: jupyterhub
    version: "4.3.2"
    repository: "https://hub.jupyter.org/helm-chart/"
    condition: jupyterhub.enabled